interface iItems {
	[index: number]: {
		id: number;
		name: string;
		stock: number;
		price_retail: number;
		price_wholesale: number;
		description?: string;
	};
}

const data: iItems = [
	{
		id: 1,
		name: "Ayam Kiloan",
		stock: 10,
		price_retail: 28000,
		price_wholesale: 26000,
		description: "Ayam boiler segar bak air surgawi",
	},
	{
		id: 2,
		name: "Keju Kiloan",
		stock: 10,
		price_retail: 70000,
		price_wholesale: 64000,
		description: "Keju itu barang mahal bung",
	},
	{
		id: 3,
		name: "Sirloin Kiloan",
		stock: 10,
		price_retail: 28000,
		price_wholesale: 26000,
		description: "Sirloin sapi asli Indonesia",
	},
	{
		id: 4,
		name: "Tenderloin Kiloan",
		stock: 10,
		price_retail: 70000,
		price_wholesale: 64000,
		description: "Tenderloin sapi asli Indonesia",
	},
	{
		id: 5,
		name: "aliquip labore culpa",
		description: "eu est consectetur officia cillum",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 6,
		name: "minim laborum ut deserunt anim",
		description: "do eiusmod eiusmod",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 7,
		name: "exercitation pariatur ut veniam aliquip",
		description: "incididunt veniam aliquip dolor proident",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 8,
		name: "consequat eu non",
		description: "aute qui irure",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 9,
		name: "do consectetur adipisicing minim dolore",
		description: "ipsum anim anim",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 10,
		name: "sunt sint consequat",
		description: "est enim velit voluptate elit",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 11,
		name: "excepteur qui consequat",
		description: "duis cillum voluptate",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 12,
		name: "exercitation adipisicing ullamco",
		description: "incididunt qui sint",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 13,
		name: "aliqua quis ut",
		description: "non aliqua reprehenderit fugiat cupidatat",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 14,
		name: "deserunt sint ad officia aliqua",
		description: "magna minim non nostrud cillum",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 15,
		name: "esse Lorem pariatur nulla occaecat",
		description: "aute non cupidatat",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 16,
		name: "aute excepteur sit velit est",
		description: "laborum Lorem fugiat",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 17,
		name: "ex velit sit ut quis",
		description: "labore voluptate cillum",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 18,
		name: "duis amet eu",
		description: "cupidatat cupidatat exercitation",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 19,
		name: "qui labore laboris voluptate et",
		description: "fugiat nulla mollit",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 20,
		name: "proident elit irure",
		description: "ea enim reprehenderit",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 21,
		name: "fugiat fugiat Lorem",
		description: "enim ex qui laborum deserunt",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 22,
		name: "ex deserunt ut",
		description: "enim duis labore mollit duis",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 23,
		name: "quis nulla culpa esse cupidatat",
		description: "incididunt sint Lorem ipsum labore",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 24,
		name: "quis esse do",
		description: "proident esse ipsum non amet",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 25,
		name: "ad est amet labore pariatur",
		description: "nostrud non dolor",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 26,
		name: "et dolore ut ut irure",
		description: "deserunt dolor irure",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 27,
		name: "velit magna sit minim culpa",
		description: "occaecat in sit",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 28,
		name: "laboris culpa aute",
		description: "nisi amet consequat",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 29,
		name: "do nulla eiusmod id proident",
		description: "nostrud incididunt aliquip veniam laborum",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 30,
		name: "aute aute cillum sint sunt",
		description: "ullamco quis irure eiusmod duis",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 31,
		name: "dolor duis veniam nisi culpa",
		description: "ex sunt exercitation",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 32,
		name: "velit amet et ullamco duis",
		description: "eiusmod magna labore ad magna",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 33,
		name: "duis pariatur aute reprehenderit nulla",
		description: "excepteur ipsum aute reprehenderit tempor",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 34,
		name: "do excepteur excepteur irure nostrud",
		description: "velit eiusmod adipisicing qui amet",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 35,
		name: "do enim aliqua",
		description: "nisi excepteur cupidatat",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 36,
		name: "adipisicing ex aute",
		description: "proident dolor irure reprehenderit ut",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 37,
		name: "ut tempor Lorem est aute",
		description: "cillum qui reprehenderit",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 38,
		name: "aliqua incididunt elit ut excepteur",
		description: "non sit velit nostrud anim",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 39,
		name: "quis sint amet exercitation officia",
		description: "dolor adipisicing officia commodo quis",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 40,
		name: "labore in magna voluptate qui",
		description: "irure cillum officia",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 41,
		name: "pariatur consequat esse",
		description: "sit in ad",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 42,
		name: "id incididunt minim est est",
		description: "ea non aute proident dolor",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 43,
		name: "in do incididunt exercitation sint",
		description: "ipsum sint irure aliqua laboris",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 44,
		name: "qui nulla dolore ea labore",
		description: "irure ex occaecat",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 45,
		name: "nostrud consequat culpa velit nisi",
		description: "anim ut eu",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 46,
		name: "nostrud qui ullamco enim in",
		description: "velit ea Lorem reprehenderit ad",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 47,
		name: "occaecat sint incididunt",
		description: "mollit consequat voluptate",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 48,
		name: "elit anim qui magna elit",
		description: "reprehenderit id elit aliqua sunt",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 49,
		name: "velit ad est",
		description: "est consectetur consectetur officia aute",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 50,
		name: "aliquip voluptate esse consequat Lorem",
		description: "minim aliqua incididunt cillum excepteur",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 51,
		name: "incididunt sit velit",
		description: "cillum culpa eiusmod",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 52,
		name: "magna elit amet consectetur reprehenderit",
		description: "voluptate qui excepteur",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 53,
		name: "cupidatat irure consectetur",
		description: "exercitation veniam dolor",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 54,
		name: "reprehenderit ea culpa pariatur id",
		description: "tempor incididunt proident laborum Lorem",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 55,
		name: "commodo aliquip nulla",
		description: "ad amet ex",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 56,
		name: "ullamco id ex ipsum dolor",
		description: "elit occaecat nisi occaecat qui",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 57,
		name: "veniam ipsum cillum magna est",
		description: "qui nisi consectetur",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 58,
		name: "aliqua est elit id cillum",
		description: "id irure dolore",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 59,
		name: "ex in reprehenderit",
		description: "incididunt id eu",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 60,
		name: "deserunt ex aliquip ipsum incididunt",
		description: "aliquip consectetur sit dolor ut",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 61,
		name: "veniam nostrud in aute cillum",
		description: "officia qui incididunt",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 62,
		name: "ea quis proident commodo elit",
		description: "proident quis sint consectetur irure",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 63,
		name: "consequat est deserunt",
		description: "ea proident Lorem dolor ipsum",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 64,
		name: "cillum do tempor",
		description: "elit do exercitation",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 65,
		name: "ea reprehenderit Lorem reprehenderit duis",
		description: "incididunt reprehenderit laborum",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 66,
		name: "ad reprehenderit elit",
		description: "do eu voluptate culpa eu",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 67,
		name: "incididunt duis amet",
		description: "veniam dolor ea commodo proident",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 68,
		name: "irure aliquip amet velit fugiat",
		description: "sunt elit irure proident anim",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 69,
		name: "ad commodo Lorem",
		description: "non aliquip eiusmod",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 70,
		name: "nulla proident labore",
		description: "cupidatat Lorem enim enim dolore",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 71,
		name: "non sunt ipsum deserunt tempor",
		description: "sit mollit eiusmod sit elit",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 72,
		name: "mollit nulla fugiat nisi sint",
		description: "sit tempor quis",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 73,
		name: "aute ad deserunt",
		description: "reprehenderit ut in ipsum proident",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 74,
		name: "nostrud sit commodo do dolore",
		description: "laboris aliqua nisi ea id",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 75,
		name: "qui labore ut cillum irure",
		description: "exercitation non exercitation",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 76,
		name: "sunt do do",
		description: "cillum Lorem cupidatat eiusmod mollit",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 77,
		name: "ut est velit",
		description: "officia nisi occaecat",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 78,
		name: "pariatur adipisicing cillum dolor laboris",
		description: "aliquip consequat et",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 79,
		name: "dolore ad Lorem",
		description: "nostrud duis incididunt nisi fugiat",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 80,
		name: "culpa adipisicing nulla eu velit",
		description: "ipsum ad velit veniam laborum",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 81,
		name: "ex ut voluptate et consectetur",
		description: "exercitation sunt non",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 82,
		name: "dolor Lorem laboris",
		description: "velit deserunt consequat laborum Lorem",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 83,
		name: "laborum dolore dolor enim elit",
		description: "irure elit culpa",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 84,
		name: "nulla commodo eiusmod",
		description: "enim nostrud anim",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 85,
		name: "pariatur dolore laboris",
		description: "officia commodo est",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 86,
		name: "veniam excepteur laboris magna incididunt",
		description: "adipisicing amet occaecat",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 87,
		name: "anim eu ex duis Lorem",
		description: "elit aute excepteur tempor incididunt",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 88,
		name: "ex anim proident",
		description: "deserunt commodo laborum eiusmod est",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 89,
		name: "culpa irure elit eiusmod sit",
		description: "est elit incididunt minim irure",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 90,
		name: "non sint sint aliquip sint",
		description: "magna occaecat anim nulla quis",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 91,
		name: "officia velit deserunt minim ut",
		description: "nulla velit aliquip duis duis",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 92,
		name: "nulla qui ut",
		description: "do occaecat sint",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 93,
		name: "occaecat est laboris consectetur magna",
		description: "consequat fugiat esse occaecat et",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 94,
		name: "ut eu est dolore sint",
		description: "voluptate ut nostrud aute velit",
		stock: 10,
		price_retail: 100000,
		price_wholesale: 8000,
	},
	{
		id: 95,
		name: "aliqua excepteur nulla",
		description: "laboris laborum elit non deserunt",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 96,
		name: "officia consectetur ut officia veniam",
		description: "sint sunt ex magna culpa",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 97,
		name: "ut aliqua minim",
		description: "nostrud duis duis",
		stock: 100,
		price_retail: 10000,
		price_wholesale: 80000,
	},
	{
		id: 98,
		name: "anim aliqua ea ullamco do",
		description: "incididunt ea magna qui excepteur",
		stock: 10,
		price_retail: 10000,
		price_wholesale: 8000,
	},
	{
		id: 99,
		name: "irure deserunt excepteur nisi sint",
		description: "ea dolor deserunt nulla nostrud",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 80000,
	},
	{
		id: 100,
		name: "fugiat consequat consectetur",
		description: "aliqua amet eiusmod",
		stock: 100,
		price_retail: 100000,
		price_wholesale: 8000,
	},
];

export default data;
